name: Deploy to GitHub Pages

on:
    push:
        branches: [main]
        paths:
            - "**/*.html"
            - "**/*.css"
            - "**/*.js"
            - "**/*.ts"
            - "package.json"
            - "package-lock.json"
            - "**/*.md"

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pages: write
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: npm
            - run: npm ci
            - run: npm run check
            - run: npm run build:release
            - name: Setup Pages
              uses: actions/configure-pages@v4
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./dist
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
